-- 1.

SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT;

-- 2.

SELECT DEPARTMENT_NAME || '의 정원은 ' || CAPACITY || ' 명입니다.' "학과별 정원"
FROM TB_DEPARTMENT;

-- 3. 

SELECT DEPARTMENT_NO
FROM TB_DEPARTMENT
WHERE DEPARTMENT_NAME LIKE '국어국문학과';

SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO LIKE (SELECT DEPARTMENT_NO
                          FROM TB_DEPARTMENT
                          WHERE DEPARTMENT_NAME LIKE '국어국문학과')
    AND STUDENT_SSN LIKE '%-2%' 
    AND ABSENCE_YN LIKE 'Y';
    
-- 4.

SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO LIKE 'A513079'
    OR STUDENT_NO LIKE 'A51309%'
    OR STUDENT_NO LIKE 'A5131%'
ORDER BY STUDENT_NAME DESC;

-- 5.

SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY >= 20
    AND CAPACITY <= 30;
    
-- 6.

SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

-- 7.

SELECT STUDENT_NAME, DEPARTMENT_NO
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

-- 8.

SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9.

SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT
ORDER BY CATEGORY;

-- 10.

SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE STUDENT_NO LIKE 'A2%'
    AND STUDENT_ADDRESS LIKE '%전주%'
ORDER BY STUDENT_NAME;