-- 서브쿼리

-- 1.

SELECT ROWNUM, EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE, SALARY, BONUS,
CASE WHEN BONUS IS NULL THEN SALARY*12
    ELSE (SALARY*12) + (SALARY * (1+BONUS))
    END AS "보너스포함연봉"
FROM EMPLOYEE E
    JOIN DEPARTMENT D ON(E.DEPT_CODE = D.DEPT_ID)
    JOIN JOB J ON(E.JOB_CODE = J.JOB_CODE)
ORDER BY 보너스포함연봉 DESC;


SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE, ROWNUM 순위
FROM (SELECT ROWNUM, EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE, SALARY, BONUS,
        CASE WHEN BONUS IS NULL THEN SALARY*12
            ELSE (SALARY*12) + (SALARY * (1+BONUS))
            END AS "보너스포함연봉"
      FROM EMPLOYEE E
        JOIN DEPARTMENT D ON(E.DEPT_CODE = D.DEPT_ID)
        JOIN JOB J ON(E.JOB_CODE = J.JOB_CODE)
      ORDER BY 보너스포함연봉 DESC)
WHERE ROWNUM < 6;


-- 2.

SELECT DEPT_TITLE, SUM(SALARY) 
FROM EMPLOYEE E
    JOIN DEPARTMENT D ON(E.DEPT_CODE = D.DEPT_ID)
GROUP BY DEPT_TITLE
HAVING SUM(SALARY) > ANY(SELECT SUM(SALARY)/5 FROM EMPLOYEE);

SELECT SUM(SALARY)/5
FROM EMPLOYEE;

-- 3.

SELECT SUM(SALARY), AVG(SALARY)
FROM EMPLOYEE;



WITH SUM_AVG AS(
    SELECT SUM(SALARY), AVG(SALARY)
    FROM EMPLOYEE
)

SELECT * FROM SUM_AVG;

