----------------------------------------------------

-- DDL

-- 1.

DROP TABLE TB_CATEGORY;

CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);



INSERT INTO TB_CATEGORY VALUES('나', NULL);

SELECT * FROM TB_CATEGORY;

-- 2.

CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);

INSERT INTO TB_CLASS_TYPE VALUES('나', NULL);


SELECT * FROM TB_CLASS_TYPE;