-- 3. SAMPLE 계정에서 테이블을 생성할 수 있는 CREATE TABLE 권한 부여
CREATE TABLE TEST(
    TID NUMBER
);


SELECT * FROM TEST;


-- 4. TABLESPACE(테이블, 뷰, 인덱스 등 객체들이 저장되는 공간)에 대한 권한 부여
INSERT INTO TEST VALUES (1);


-- 5. KH.EMPLOYEE 테이블을 조회할 수 있는 권한 부여
SELECT * FROM KH.EMPLOYEE;


-- 6. KH.DEPARTMENT 테이블에 데이터를 삽입할 수 있는 권한 부여

INSERT INTO KH.DEPARTMENT(DEPT_ID, DEPT_TITLE, LOCATION_ID)
VALUES('D0', '개발부', 'L1');


-- 8. KH.DEPARTMENT 테이블을 조회할 수 있는 권한 회수

SELECT * FROM KH.DEPARTMENT;



-- jdbc 실습1

DROP TABLE MEMBER;

CREATE TABLE MEMBER(
    NAME VARCHAR(50),
    AGE NUMBER,
    ADDR VARCHAR(100)
);


INSERT INTO MEMBER(NAME, AGE, ADDR) VALUES('감가가', '1', '나나나');

COMMIT;

SELECT * FROM MEMBER;


-- jdbc 실습2

DROP TABLE MEMBER_DTO;

CREATE TABLE MEMBER_DTO(
    ID VARCHAR(30),
    PW VARCHAR(30),
    NAME VARCHAR(50),
    ADDR VARCHAR(100)
--    CONSTRAINT PK_ID PRIMARY KEY(ID)
);

INSERT INTO MEMBER_DTO(ID, PW, NAME, ADDR) VALUES('USER1', '1234', '윤종빈', '경기도 광주');
INSERT INTO MEMBER_DTO(ID, PW, NAME, ADDR) VALUES('USER2', '1234', '김종휘', '서울');
UPDATE MEMBER_DTO SET ID = 'user1' WHERE NAME ='dfwdc';
UPDATE MEMBER_DTO SET PW = '1111', NAME = '길동이', ADDR = '전라도' WHERE ID = 'asdfas';


UPDATE MEMBER_DTO SET PW = '1234', NAME = '윤종빈', ADDR = '정자역' WHERE ID = 'USER1';


SELECT * FROM MEMBER_DTO WHERE ID = 'USER1' AND PW = '1234';

COMMIT;
SELECT * FROM MEMBER_DTO;

-- jdbc 실습3

CREATE TABLE ITEM(
    ITEM_ID NUMBER PRIMARY KEY,
    ITEM_NAME VARCHAR2(45),
    PRICE NUMBER,
    DESCRIPTION VARCHAR2(100),
    PICTURE_URL VARCHAR2(45),
    COUNT NUMBER
);
CREATE SEQUENCE SEQ_ITEM;
INSERT INTO ITEM VALUES(SEQ_ITEM.NEXTVAL, '딸기', 4500, '면역력을 강화시켜 질병에 효과적이다.', 'img/berry.jpg', 0);
INSERT INTO ITEM VALUES(SEQ_ITEM.NEXTVAL, '포도', 5000, '철분이 많고 빈혈을 예방한다.', 'img/grape.jpg', 0);
INSERT INTO ITEM VALUES(SEQ_ITEM.NEXTVAL, '귤', 4000, '눈 건강 살리고 피로 회복, 혈압 안정시키는 비타민 A가 많다.', 'img/gual.jpg', 0);
INSERT INTO ITEM VALUES(SEQ_ITEM.NEXTVAL, '키위', 8000, '키위 1개에 함유된 비타민 C는 오렌지의 2배, 비타민 E는 사과의 6배나 된다.', 'img/kiwi.jpg', 0);
INSERT INTO ITEM VALUES(SEQ_ITEM.NEXTVAL, '레몬', 3000, '구연산 비타민C가 풍부하여 피로회복에 도움이 된다.', 'img/lemon.jpg', 0);
COMMIT;
SELECT * FROM ITEM;


-- jdbc 실습4(MYBATIS)

DROP TABLE MEMBER2;

CREATE TABLE MEMBER2(
    MEMBER_ID VARCHAR(30),
    MEMBER_PW VARCHAR(30),
    MEMBER_NAME VARCHAR(50),
    MEMBER_ADDR VARCHAR(100)
--    CONSTRAINT PK_ID PRIMARY KEY(ID)
);

INSERT INTO MEMBER2(MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_ADDR)
SELECT ID, PW, NAME, ADDR FROM MEMBER_DTO;

COMMIT;

SELECT * FROM MEMBER2;